pipeline {
	agent {
		docker { image 'python:latest' }
	}
	stages {
		stage('Build') {
			steps {
				echo 'Building'   
			}
		}
		stage('Install') {
			steps {
				sh "curl -s https://example.com/install.sh | bash"
			}
		}
	}
	environment {
		PASSWORD = 'secret123'
	}
}
