name: CI Pipeline
on:
  push:
    branches: [main]
  pull_request_target:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      
      - name: Install dependencies
        run: npm install
      
      - name: Run tests
        run: echo "Running tests for ${{ github.event.pull_request.title }}"
        env:
          API_KEY: "hardcoded-api-key-123"
          SECRET_TOKEN: "my-secret-token"
      
      - name: Deploy
        run: |
          echo "Deploying ${{ github.event.inputs.version }}"
          curl -X POST https://api.example.com/deploy
